[package]
name = "robocar"
version = "0.1.0"
authors = ["Joshua Rutschmann <joshua@rutschmann.tech>"]
edition = "2018"

[dependencies]
rust_gpiozero = "0.2.0"
nix = "0.13.0"
mfrc522 = "0.2.0"
linux-embedded-hal = "0.2.2"
simplelog = "^0.6.0"
log = "0.4"
libc = "*"